name: docker-compose-actions-workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build images
        run: docker-compose up -d
      - name: docker push
        run: docker-compose push
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mohamedabotir/recycleit
